### ISSUE TITLE
ruby blocks support

### ISSUE THREAD

**Issue by yamlCase** [1nVitr0/plugin-vscode-blocksort#10]
please add support for ruby's non-curly-brace blocks. Below are some details that should cover 95% of use cases

# Keywords

## end:
regex for line beginning with optional space chars and "end".  because ruby has an implicit return statement in the `end` keyword, it can have methods attached to manipulate this return. 

Examples:
```
end               # this just returns the last execution
end.reverse       # returns an array in reverse order
end[2]            # returns the second element of an array
end.upcase        # non array manipulation
end.map do |var|  # chaining another call
  code
end
```

this regex should cover these use cases
```
^\s*end[\.[]*(\s|$)
```

## def:
regex for line beginning with optional space chars and "def" followed by space and other chars.
```
^\s*def\s*
```

## do:
can be at the end of a line, or followed by `|var|`
```
\sdo\s*(\|[^|]+\|\s*)$
```

# Examples
creating methods:
```
def method
  code
end
```

calling methods
```
method do
  code
end
```

loops:
```
list.each do |vars|
  code
end
```

# References
'Using the "end" keyword in Ruby'
- by @jules27
- https://gist.github.com/jules27/3668380

'Mastering Ruby Blocks in Less Than 5 Minutes'
- by (unknown author)
- https://mixandgo.com/learn/ruby-blocks

**Comment by yamlCase** [comment]
By the way, I just wanted to say thank you for writing this extension.  It saved my bacon trying to diff chef recipes.  Had to replace all the "do .. end" with "{ .. }" to get the parsing to work, but besides that it really worked great.

**Comment by 1nVitr0** [comment]
Thanks, no problem :)

Okay, after some personal issues (I dropped my phone onto a plate an destroyed the screen), I have finally come around to adding non-bracketed block support.

I am still trying to keep this extension language independent, hence adding new block styles is more complicated than it seems. In the future I may have to resort to language specific blocks. Fell free to test once the checks are passed and the new version is deployed.

The way I solved this, is by adding 'end.*' lines to the `indentIgnore` list. This means, they will be counted as part of the current block instead of a new one. This results in lines classified as `indentIgnore` 'sticking' to other blocks. The same method is used to support C++-style blocks where `{` is on a new line. You can now add more regexes using the configuration `blocksort.indentIgnoreMarkers` in case you need them.

**Comment by 1nVitr0** [comment]
I'll close for now, will reopen if any new problems come up

**Comment by yamlCase** [comment]
Yea when I started digging into the variations on do..end, I was surprised at all the ways it can differ.  Thanks for the update!
