### ISSUE TITLE
#98ca9ea Optional expand selection

### ISSUE THREAD

**Issue by anon97945** [1nVitr0/plugin-vscode-blocksort#58]
Hello,

is it possible to have [98ca9ea](https://github.com/1nVitr0/plugin-vscode-blocksort/commit/98ca9eae41553a24771167509852b5369a95f6ca) optional? i sometimes want only sort selection....

**Comment by 1nVitr0** [comment]
@anon97945 Yes, absolutely! I was planning on adding this anyway. But since you are interested, I'd be happy for some input. When you have the following selection:

```ts
switch (test) {
>>> BEGIN SELECTION
  case 'a':
    console.log('a');
    break;
  case 'b':
    if (something) {
      console.log('something'):<<< END SELECTION
    } else {
      consoe.log('else');
    }
    break;
  default:
    console.log('default');
}
```

Would you expect the selection to end up:

- **(a) Exactly as is**

- **(b) Folding marker complete**
> ```ts
> switch (test) {
> >>> BEGIN SELECTION
>   case 'a':
>     console.log('a');
>     break;
>   case 'b':
>     if (something) {
>       console.log('something'):
>     } else {
>       consoe.log('else');
>     }<<< END SELECTION
>     break;
>   default:
>     console.log('default');
> }
> ```

- **(c) Indentation and Folding Marker complete**
> ```ts
> switch (test) {
> >>> BEGIN SELECTION
>   case 'a':
>     console.log('a');
>     break;
>   case 'b':
>     if (something) {
>       console.log('something'):
>     } else {
>       consoe.log('else');
>     }
>     break;<<< END SELECTION
>   default:
>     console.log('default');
> }
> ```

- **(d) configurable between all 3 options**

All options should not be that complicated to implement as the new selection expansion algorithm already supports similar options. The configuration will end up being global (or per language) as having different commands would flood the command picker with too many similar commands. Although there would be separate options for when a selection is active vs. a single cursor.

Right now there is only the configuration `blocksort.alwaysExpandOverSeparators`, which  controls, whether the selection is expanded over empty lines:

```ts
>>> BEGIN SELECTION
a
b<<< END SELECTION

c
```

vs

```ts
>>> BEGIN SELECTION
a
b

c<<< END SELECTION
```

**Comment by 1nVitr0** [comment]
#59 should address this. I opted for a choice between the options. You should now be able to control the expansion by setting the configuration for `expandSelection` or `expandCursor`.

`true` will yield full expansion, while `false` will keep the selection as-is. The full configuration is:

```json
{
  "expandLocally": boolean,
  "expandOverEmptyLines": boolean,
  "foldingComplete": boolean,
  "indentationComplete": boolean
}
```
