### ISSUE TITLE
Feature request: Numerical sorting

### ISSUE THREAD

**Issue by freddo256** [1nVitr0/plugin-vscode-blocksort#74]
We use this plugin a lot for sorting yml files containing route tables and stuff.
The block sorting feature of this plugin is already really helpful, but it would be cool to add a numerical sorting feature to it.

For example instead of this:
```
- network: 10.111.1.0
  gateway: 10.111.1.1
  prefix: 24
- network: 10.2.1.0
  gateway: 10.2.1.1
  prefix: 24
- network: 10.20.1.0
  gateway: 10.20.1.1
  prefix: 24
```
Parse numbers and sort like this:
```
- network: 10.2.1.0
  gateway: 10.2.1.1
  prefix: 24
- network: 10.20.1.0
  gateway: 10.20.1.1
  prefix: 24
- network: 10.111.1.0
  gateway: 10.111.1.1
  prefix: 24
```

**Comment by 1nVitr0** [comment]
@freddo256 Can you try enabling "Natural Sorting"? This might already do what you want. It does add some overhead, which is why it is disabled by default, but shouldn't bee too bad.

Internally, this pads the numbers with leading zeros before sorting, as specified in the "Natural Sorting" options (default is up to length 9).
